### ISSUE TITLE
大佬求分享源码

### ISSUE THREAD

**Issue by lc5259** [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1#1]
大佬你好，能分享下Microsoft.Practices.EnterpriseLibrary.Common Microsoft.Practices.EnterpriseLibrary.Data  这两个库的源码吗，方便的话加我微信： 1433420541，

**Comment by hrx521** [comment]
Dependencies · hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1 (github.com)




大风
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 
大佬你好，能分享下Microsoft.Practices.EnterpriseLibrary.Common Microsoft.Practices.EnterpriseLibrary.Data  这两个库的源码吗，方便的话加我微信： 1433420541，

**Comment by lc5259** [comment]
Microsoft.Practices.EnterpriseLibrary.Common Microsoft.Practices.EnterpriseLibrary.Data 这两个微软的企业库有源码吗

**Comment by hrx521** [comment]
Microsoft.Practices.EnterpriseLibrary_NetStandard2.1/Src at master · hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1 (github.com)
这里有一个data的源码，另一个项目的源码好像就是sqlce的那个路径。时间有点久了，我有点忘了。再帮你找找


大风
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 
Microsoft.Practices.EnterpriseLibrary.Common Microsoft.Practices.EnterpriseLibrary.Data 这两个微软的企业库有源码吗

**Comment by lc5259** [comment]
好的好的，data的我有了，麻烦找一个Microsoft.Practices.EnterpriseLibrary.Common 的源码啦，感谢！

**Comment by hrx521** [comment]
这里有三份源码，是我改动之前的原始代码，应该有你想要的东西。希望对你有用。当时我好像也是从github上找到的，但是查了下没有找到记录。




大风
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 
Microsoft.Practices.EnterpriseLibrary.Common Microsoft.Practices.EnterpriseLibrary.Data 这两个微软的企业库有源码吗

**Comment by lc5259** [comment]
三份源码在哪里啊，我好像没看到啊

**Comment by hrx521** [comment]
上一封邮件的附件中哦

&nbsp;


大风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月13日(星期五) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 
三份源码在哪里啊，我好像没看到啊

**Comment by lc5259** [comment]
是不是被邮箱拦截了啊，我在qq邮箱中也没有看到附件啊

**Comment by hrx521** [comment]
我又发了一次，在这封信中的附件中，有3个附件。Github我被墙着呢，不然可以上传到它上面。




大风
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 
是不是被邮箱拦截了啊，我在qq邮箱中也没有看到附件啊

**Comment by lc5259** [comment]
我这还是没看到，能麻烦传到百度网盘里，分享个百度网盘链接嘛

刘闯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1)





 我又发了一次，在这封信中的附件中，有3个附件。Github我被墙着呢，不然可以上传到它上面。 
 
 
 
 
 大风 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年10月13日(星期五) 下午4:53 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1] 大佬求分享源码 (Issue #1) 
 
 
 
 
 
   
 是不是被邮箱拦截了啊，我在qq邮箱中也没有看到附件啊

**Comment by hrx521** [comment]
直接给你上传到现在这条评论里了。请自行下载吧
[enterprise-library-common-infrastructure-master.zip](https://github.com/hrx521/Microsoft.Practices.EnterpriseLibrary_NetStandard2.1/files/12915889/enterprise-library-common-infrastructure-master.zip)
